export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GOOGLE_USER = "GOOGLE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SIGNUP_PROFESSIONAL = "SIGNUP_PROFESSIONAL";
